url: "https://AntsThatWander.github.io"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Jonghyeop Lim
subtitle: preliminary developer! All hail Formica Japonica!

# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: Skills & Offers
    link: /skills-and-offers
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  - text: My Resume
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: github
    link: https://github.com/AntsThatWander
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square



    
