url: "https://AntsThatWander.github.io"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Jonghyeop Lim
subtitle: Preliminary developer! 

# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""


# Socialmedia Icons
social_icons:
  - name: github
    link: https://github.com/AntsThatWander
    icon: fab fa-github-square





    
