url: "https://AntsThatWander.github.io"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Jonghyeop Lim
subtitle: Preliminary developer! 
description: Welcome to my blog, travelers!

# Side Menu Links
menu:
  - text: Profile
    link: /AntsThatWanderPage
    icon: ""

menu:
  - text: Minecraft ideas
    link: /Minecraft
    icon: ""
    
menu:
  - text: Game ideas
    link: /GameDev
    icon: ""


# Socialmedia Icons
social_icons:
  - name: github
    link: https://github.com/AntsThatWander
    icon: fab fa-github-square





    
